package org.opendatamesh.platform.pp.marketplace.rest.v1.resources.executors;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Date;
import java.util.List;
import java.util.Map;

@Schema(description = "Request for marketplace operations")
public class MarketplaceExecutorRequestRes {
    @Schema(description = "Version of the resource")
    private String v;

    @Schema(description = "Operation type (MARKETPLACE_SUBSCRIBE or MARKETPLACE_UNSUBSCRIBE)")
    private String operation;

    @Schema(description = "Request information")
    private RequestInfo request;

    public String getV() {
        return v;
    }

    public void setV(String v) {
        this.v = v;
    }

    public String getOperation() {
        return operation;
    }

    public void setOperation(String operation) {
        this.operation = operation;
    }

    public RequestInfo getRequest() {
        return request;
    }

    public void setRequest(RequestInfo request) {
        this.request = request;
    }

    @Schema(description = "Request information for marketplace operations")
    public static class RequestInfo {
        @Schema(description = "Name of the request")
        private String name;

        @Schema(description = "Identifier of the request, generated by the Marketplace Service")
        private String identifier;

        @Schema(description = "Provider information")
        private ProviderInfo provider;

        @Schema(description = "Consumer information")
        private ConsumerInfo consumer;

        @Schema(description = "Requester information")
        private RequesterInfo requester;

        @Schema(description = "Additional properties that can be configured dynamically")
        private Map<String, Object> properties;

        @Schema(description = "The date on which access starts to be valid")
        private Date startDate;

        @Schema(description = "The date on which access expires")
        private Date endDate;

        // Getters and setters for RequestInfo
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getIdentifier() {
            return identifier;
        }

        public void setIdentifier(String identifier) {
            this.identifier = identifier;
        }

        public ProviderInfo getProvider() {
            return provider;
        }

        public void setProvider(ProviderInfo provider) {
            this.provider = provider;
        }

        public ConsumerInfo getConsumer() {
            return consumer;
        }

        public void setConsumer(ConsumerInfo consumer) {
            this.consumer = consumer;
        }

        public RequesterInfo getRequester() {
            return requester;
        }

        public void setRequester(RequesterInfo requester) {
            this.requester = requester;
        }

        public Map<String, Object> getProperties() {
            return properties;
        }

        public void setProperties(Map<String, Object> properties) {
            this.properties = properties;
        }

        public Date getStartDate() {
            return startDate;
        }

        public void setStartDate(Date startDate) {
            this.startDate = startDate;
        }

        public Date getEndDate() {
            return endDate;
        }

        public void setEndDate(Date endDate) {
            this.endDate = endDate;
        }
    }

    @Schema(description = "Provider information for the request")
    public static class ProviderInfo {
        @Schema(description = "Data product fully qualified name")
        private String dataProductFqn;

        @Schema(description = "Data product ports fully qualified names")
        private List<String> dataProductPortsFqn;

        public String getDataProductFqn() {
            return dataProductFqn;
        }

        public void setDataProductFqn(String dataProductFqn) {
            this.dataProductFqn = dataProductFqn;
        }

        public List<String> getDataProductPortsFqn() {
            return dataProductPortsFqn;
        }

        public void setDataProductPortsFqn(List<String> dataProductPortsFqn) {
            this.dataProductPortsFqn = dataProductPortsFqn;
        }
    }

    @Schema(description = "Consumer information for the request")
    public static class ConsumerInfo {
        @Schema(description = "Consumer type")
        private String type;

        @Schema(description = "Consumer identifier")
        private String identifier;

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getIdentifier() {
            return identifier;
        }

        public void setIdentifier(String identifier) {
            this.identifier = identifier;
        }
    }

    @Schema(description = "Requester information for the request")
    public static class RequesterInfo {
        @Schema(description = "Requester type (user)")
        private String type;

        @Schema(description = "Requester identifier (email)")
        private String identifier;

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getIdentifier() {
            return identifier;
        }

        public void setIdentifier(String identifier) {
            this.identifier = identifier;
        }
    }
} 